name: main build
on:
  push:
    branches:
      - 'main'
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/workflows/core
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: yarn ci:publish-package
